version: '3.5'

services:
  db2es:
    networks:
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${MICROSERVICE_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: PathPrefix:/api/${MICROSERVICE_NAME}
        traefik.backend: ${MICROSERVICE_NAME}
      placement:
        constraints:
          - node.role == worker
          - node.labels.workerid == ${DESIRED_WORKER_ID}
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  traefik-net:
    external: true
